server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: 1210

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

